### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by gadelkareem** [anacrolix/confluence#14]
I limited the requests to 10 concurrent requests to the DHT server and dropped the torrent from the client after collecting the metainfo:
```
var limiter = make(chan struct{}, 10)
func findTorrent(w http.ResponseWriter, r *http.Request) *torrent.Torrent {
	limiter <- struct{}{}
	t := torrentForRequest(r)
	defer func() {
		<-limiter
		t.Drop()
	}()
	if nowait, err := strconv.ParseBool(r.URL.Query().Get("nowait")); err == nil && nowait {
		select {
		case <-t.GotInfo():
		default:
			http.Error(w, "info not ready", http.StatusAccepted)
			return nil
		}
	} else {
		// w.WriteHeader(http.StatusProcessing)
		select {
		case <-t.GotInfo():
		case <-r.Context().Done():
			return nil
		}
	}

	// w.WriteHeader(http.StatusOK)

	return t
}
```
Yet the memory usage gets up to 2GB in its peak. Here is a sample from stackimpact:
![screenshot 2019-03-08 at 12 15 35 am](https://user-images.githubusercontent.com/1441127/53996105-8c0a4200-4137-11e9-81d4-70af51ae7244.png)

Is it normal that the communication requires that much ram? Could it be a problem with the bencode serialisation?

**Comment by anacrolix** [comment]
Where are you deriving the heap allocation value? Often people conflate the virtual and resident memory usage, I want to rule that out.

**Comment by gadelkareem** [comment]
it is the default stackimpact allocation https://stackimpact.com/blog/go-profiler-internals/

**Comment by anacrolix** [comment]
Okay that makes sense. It's likely due to query rate limiting due to the conntrack implementation. I intend to redesign this sometime. In the meanwhile, try calling `SetNoMaxEntries` and setting `Timeout` to a function that returns zero duration on the `ConnectionTracking` field in the dht `ServerConfig` for your instance.

**Comment by gadelkareem** [comment]
I made some tests using github.com/shiyanhui/dht and the memory/CPU usage is much lower.

**Comment by anacrolix** [comment]
@gadelkareem try again now with the *latest* version of `anacrolix/dht`.

**Comment by gadelkareem** [comment]
Thanks @anacrolix will let you know when I get the time.

**Comment by anacrolix** [comment]
If this isn't fixed by previous changes, https://github.com/anacrolix/dht/commit/8f69499a9cd0dfd8bf846abe05bda3f17197561d will most certainly do it.

**Comment by anacrolix** [comment]
See `v1.5.0`.
