### ISSUE TITLE
Request: add a way to disable ipv6

### ISSUE THREAD

**Issue by d33tah** [anacrolix/confluence#15]
Thanks for the tool! It works pretty nicely, but for some torrents the client is getting stuck with the following messages in the log:

```
go-libutp: 2019/11/18 19:47:45 callbacks.go:75: error sending packet: write udp6 [::]:50007->[2403:6200:8917:deec:7850:c7ec:20c8:e139]:34515: sendto: cannot assign requested address
```

I'm guessing this is because my host doesn't support ipv6. Could it be possible to disable ipv6 support entirely so that Confluence doesn't waste time on it?

**Comment by anacrolix** [comment]
@d33tah yes, pass a `torrent.Client` to `Handler.TC` configured with [`DisableIpv6`](https://github.com/anacrolix/torrent/blob/v1.9.0/config.go#L25) set to `true`.

**Comment by anacrolix** [comment]
This would appear to be solved.
