### ISSUE TITLE
Request: add a way to kill a specific torrent?

### ISSUE THREAD

**Issue by d33tah** [anacrolix/confluence#16]
I'm writing a program that's going to download small chunks of lots of different torrents. In many cases, it will time out and then I don't need Confluence to spend any more time trying to find hosts with the file. Could you add a way to stop downloads for a given torrent file so that it doesn't appear in the `/status` endpoint and its cache is wiped?

**Comment by anacrolix** [comment]
confluence will call `Handler.OnTorrentGrace`, after a `Torrent` is not used for a period of `Handler.TorrentGrace`. See https://github.com/anacrolix/confluence/blob/v1.3.0/confluence/handler.go#L12. Most implementations will just drop the `Torrent`, but you can also do other things like clear any data etc. at your whim. Is that the feature you're after?

**Comment by d33tah** [comment]
Yes, I guess so. Thanks for the pointer, I guess I'll implement this myself at this point - it might be that I end up not needing this feature anyway, so unless somebody else asks for it, there might be better requests to fulfill.

Also, thanks for a quick response! :)

**Comment by anacrolix** [comment]
This is definitely solved, so far as you've described the problem.
