### ISSUE TITLE
More natural paths for accessing data

### ISSUE THREAD

**Issue by boramalper** [anacrolix/confluence#17]
Instead of 

    GET /data?ih=<infohash in hex>&path=<display path of file declared in torrent info>

what about 

    GET /data/<infohash in hex>/<display path of file declared in torrent info>

This syntax would also allow us to display "directory listings", when the path following the infohash is not "complete" (i.e. points to a file).

Imagine the following torrent:
```
/
    dir1/
        a.txt
        b.txt
    dir2/
        c.txt
```

A GET request to `/data/<infohash>/dir1` shall display a directory listing of `dir1` with files `a.txt` and `b.txt`; just as a regular web server serving static files would do.

**Comment by anacrolix** [comment]
That seems reasonable. There's no reason this couldn't be done for `path` query parameters that match a prefix of an actual file path too. I wonder at your use-case where URL paths are preferable to query parameters.

**Comment by boramalper** [comment]
I was thinking of developing an HTTP -> BitTorrent gateway (similar to IPFS gateways) before I found confluence, and my idea was to be able to serve static websites too. If we use natural paths, content can be addressed using relative paths whereas query parameters do not allow that.

It also helps with "discoverability": directory listings help.

If you are interested, I can try a PR sometime soon.

**Comment by anacrolix** [comment]
Yes, that sounds ideal. Confluence also acts as a source for arbitrary metainfos, something projects like your magnetico can benefit from.

**Comment by anacrolix** [comment]
I have another project in the works that does something similar. It uses domain names to achieve origin isolation and serve static websites without needing hacks to achieve expected paths @boramalper .

**Comment by boramalper** [comment]
I presume you mean something like:

    http://<INFOHASH>.example.com/path/to/file

Is this other project public yet? Are you planning to continue maintaining Confluence?

**Comment by anacrolix** [comment]
Not public yet. Yes, in fact I'm reusing confluence for part of it, for now.

**Comment by anacrolix** [comment]
> ```
> http://<INFOHASH>.example.com/path/to/file
> ```
Yes
