### ISSUE TITLE
Make /metainfo return JSON too

### ISSUE THREAD

**Issue by boramalper** [anacrolix/confluence#18]
I think to allow easier processing on client-side, /info endpoint shall return JSON-ified version of info dictionaries.

[Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) can be used to control the format (JSON or bencoded), or a wholly new endpoint can be conceived.

**Comment by anacrolix** [comment]
That's an excellent idea. I think I'd prefer to specifically match the JSON mime-type from the `Accept` header.
