### ISSUE TITLE
This becomes a rabid powerhouse

### ISSUE THREAD

**Issue by faddat** [anacrolix/confluence#2]
......the second that it can use WebTorrent.  

Any ideas on how to approach an implementation?  I know only this:  @feross said to "wrap bittorrent in webrtc." Once I have an idea of how to do that, I'll certainly go about trying to do it.

**Comment by anacrolix** [comment]
Yeah, this project is a great idea :D. I and several others are using it to simplify access to BitTorrent. WebTorrent support would be fantastic, confluence already acts as a proxy between HTTP and BitTorrent, adding that makes the name even more appropriate.

**Comment by anacrolix** [comment]
Perhaps you can reference this issue in whatever place the WebRTC spec is being tracked.

**Comment by anacrolix** [comment]
See https://github.com/anacrolix/torrent/issues/138.

**Comment by anacrolix** [comment]
This is more appropriately tracked in https://github.com/anacrolix/torrent/issues/138, and should only require an update when it's ready.
