### ISSUE TITLE
When will the confluence client support webtorrent?

### ISSUE THREAD

**Issue by meotimdihia** [anacrolix/confluence#20]
Currently, I want to test it, seed thousands of exist files and torrents.
I saw lib torrent supported it: https://github.com/anacrolix/torrent/issues/138. 
The problem is `./cmd/torrent` don't detect exist file and will download it, I read https://github.com/anacrolix/torrent/issues/374,  but it can't do in command line?

**Comment by anacrolix** [comment]
Confluence does support webtorrent, if it pulls an appropriate version of anacrolix/torrent. I could pull a recent version into master now. You must package your files into torrents before you can distribute them through a BitTorrent client.

**Comment by anacrolix** [comment]
From your module that uses anacrolix/confluence, or a clone of anacrolix/confluence itself, call `go get github.com/anacrolix/torrent@master`.

**Comment by meotimdihia** [comment]
I will try and report again.
