### ISSUE TITLE
How to get path of each file in the torrent?

### ISSUE THREAD

**Issue by chaos369** [anacrolix/confluence#27]
According to the interface, the path parameter is needed to get the actual data.
 Is there any way to list the files in a infohash?  How to parse the result of   /info?ih=<infohash in hex>   ?
 
GET /data?ih=<infohash in hex>&path=<display path of file declared in torrent info>.

**Comment by anacrolix** [comment]
The contents of an info are per https://pkg.go.dev/github.com/anacrolix/torrent@v1.20.0/metainfo#Info, which can be unmarshalled with https://pkg.go.dev/github.com/anacrolix/torrent@v1.20.0/bencode.

**Comment by chaos369** [comment]
Got it.
