### ISSUE TITLE
Set data Dir using flags.

### ISSUE THREAD

**Issue by bubundas17** [anacrolix/confluence#35]
Currently, Confluence puts all the cache, Incomplete files and other files where we are executing the program. 

It would be nice to be able to specify a data dir where Confluence will store all of its files.

**Comment by anacrolix** [comment]
Does changing the working directory work for you? There's also -fileDir, or a customized URI for -sqliteStorage.

**Comment by bubundas17** [comment]
Yes, changing working directory works.
In my use case I have another service beside confluence. And it is a bit
annoying to change working directory and execute confluence and then switch
back and run another service.

In my opinion having a flag for data directory looks bit more elegant than
having to change the working directory.

**Comment by anacrolix** [comment]
It is opinionated, but I do believe that working directories are not used enough, and allow for consistent and predictable behaviour. I'm happy to accept PRs or evidence to the contrary. I think what you described above is easily handled with something like
```
(cd /confluence/config/dir && confluence) &
some other service
wait
```

**Comment by bubundas17** [comment]
Yes, I have changed the working directory and now it works. And I have spawned another process for the other service. 

And do you have any plans to port go-libutp package to native GO. So it can be compiled without CGO.

**Comment by bubundas17** [comment]
> 

I asked it because I was having issues building this for Android devices. 
I am not familiar with Zig. Can we use it to build for Android as well?
