### ISSUE TITLE
Route for adding trackers

### ISSUE THREAD

**Issue by bsuh** [anacrolix/confluence#5]
I would like to add trackers from magnet URIs without knowing info bytes.

**Comment by anacrolix** [comment]
Post a metainfo with the announce list to /metainfo?ih=infohash.

**Comment by bsuh** [comment]
Ah I was under the impression you would need all the info in a torrent file for that route.

**Comment by anacrolix** [comment]
I've tried to improve the documentation on this. Feel free to make improvements, thanks.
