### ISSUE TITLE
Add options to set half open limit and established connections limit

### ISSUE THREAD

**Issue by bsuh** [anacrolix/confluence#7]
I've noticed that with the 80 half open limit on FreeBSD, the time to gain peers is slow. It seems like confluence is mostly stuck on waiting for connection establishment timeouts if a lot of peers don't have open ports.

**Comment by anacrolix** [comment]
It might be worth adding tests that check what the connection timeout behaviour is for uTP and TCP for the most pathological listener cases. For example a friendly peer might send a reset or denial response as opposed to leaving us hanging for the full timeout. Are you aware of any numbers in this area? I wonder if the libutp wrapper is handling those responses for UDP.

**Comment by bsuh** [comment]
What do you mean by "this area"? I have no clue how uTP works and for TCP the connection timeout is likely longer than the minute timeout set here https://github.com/anacrolix/torrent/blob/53ee52e26acab3191173e76db00a7b144a1db554/client.go#L632, so I'm not sure the TCP connection timeout number matters.

**Comment by anacrolix** [comment]
I mean what numbers do you have around how long your dials are typically taking. How often are you reaching the full 1 minute timeout? Just because a port isn't open doesn't mean the full timeout will be used.

**Comment by anacrolix** [comment]
Related to https://github.com/anacrolix/torrent/issues/55.

**Comment by anacrolix** [comment]
The necessary values are now exposed in the torrent package: https://github.com/anacrolix/confluence/blob/4f2007ae9ee61f9f0a443c9a7dc4ad6545cbf84a/main.go#L86.

**Comment by anacrolix** [comment]
I think this is fixed.
