### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by iamale** [anacrolix/confluence#9]
Probably MPL2 as well, just like [anacrolix/torrent](https://github.com/anacrolix/torrent)?

**Comment by iamale** [comment]
(I'd also like to use this chance to say thank you for the amazing torrent-related projects you're doing!)

**Comment by anacrolix** [comment]
Thanks. Yes MPL2 is correct.

**Comment by iangudger** [comment]
Would it be possible for you to add a LICENSE file to the repo? I can't use this without an official license. Thanks.
